version: "3.8"

services:
  app:
    build:
      context: .         # Корень проекта
      dockerfile: Dockerfile
    container_name: aspnet_app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      # Монтируем локальные папки вместо томов
      - ./Persistent/Data:/app/Persistent/Data
      - ./Persistent/Resources:/app/Persistent/Resources
      - ./Persistent/Images:/app/Persistent/Images
    expose:
      - "5000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/uakhutir.com/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/uakhutir.com/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - app
    restart: always
